@echo off
echo Starting Eventura Backend Server...
cd /d "C:\EVENTURA APP\eventura_app_flutter_code\backend"
start "Eventura Backend" cmd /k "npm start"
echo Backend server is starting in a new window...
